### ISSUE TITLE
No path in links

### ISSUE THREAD

**Issue by cblavier** [mgwidmann/scrivener_html#2]
Hey,

My pagination menu is generated correctly, excepted there is no path in generated links : there is only the query string part (something like ```href="/?page=XXX"```). So the links consistently lead me to the root path.

I'm displaying a paginated list of POIs on a shop edit form ("/shop/:id/edit"). I understand that scrivener doesn't manage to guess the correct path.

**Comment by mgwidmann** [comment]
Can you give me a code snippet?

**Comment by mgwidmann** [comment]
Now that I remember correctly, the code always goes to the index route as you can see here:

https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html.ex#L109

I think that needs to be an option so you can do something like this:

```
<%= pagination_links(@conn, @pois, [@shop], action: :edit) %>
```

The code would then attempt to generate links to `shop_poi_path(@conn, :edit, @shop.id)`, but thats not what you want. Instead you'd like it to go to `shop_path(@conn, :edit, @shop.id)`, which means you'd have to supply `path_fn: &shop_path/3` additionally. However, I suspect that won't work since it'll be applying 4 arguments instead of 3.

Looks like theres 2 things that need to change:
  1. Accept a possible `:action` change instead of hard coding `:index`
  2. Use the arity number of the `args` length instead of trying to guess

If you'd like to submit a PR you may, or I'll try to get to this whenever I can.

**Comment by cblavier** [comment]
I'm sorry, I don't feel confident enough yet at writing Elixir code to submit a PR.

Still, I have (maybe naive) questions : 
- why isn't `pagination_links` simply using current path ?
- shouldn't you provide, as a fallback, the ability to give the path as a string (not as a function)

**Comment by mgwidmann** [comment]
The problem you're experiencing is because its hard coded to use the `:index` route. Additionally, if you aren't using Phoenix it will not guess the route automatically (but I assume you are).

**Comment by cblavier** [comment]
I confirm I'm using Phoenix.

I finally worked around the issue using a custom path function:
```elixir
def pagination_path(_conn,_action,args) do
  "?page=#{args[:page]}"
end
```
```haml
= pagination_links @conn, @page, path: &pagination_path/3
```

**Comment by mgwidmann** [comment]
Ah good. I'll still try to get this fixed in master. Thanks for reporting it!

**Comment by mgwidmann** [comment]
@cblavier OK, I've pushed up a new version which should allow you to do the following:

```
<%= pagination_links(@conn, @pois, [@shop], action: :edit) %>
```

Please try it out and let me know how things work out for you! Thanks for reporting this!

**Comment by steve0hh** [comment]
Don't know if this is a bug.

```
<%= pagination_links @conn, @question.answer, [@question], action: :show, path: &explore_question_path/3 %>
```

Doesn't work. Why not just provide an option which just appends the `?page=n` to the back of the url?

As @cblavier comment works fine:

```
def pagination_path(_conn,_action,args) do
  "?page=#{args[:page]}"
end
```

As with most use cases, we'll be at that particular page while using the html helper, we just need the `?page=n` parameter to be appended. Hence no need for guessing of URL which equates to less issues on it. 😄

**Comment by mgwidmann** [comment]
In your case it looks like `@question.answer` is a map that doesn't have they key `:answer`. You should also use the `&explore_question_path/4` if you're providing the path, since that function takes as the last parameter the query string arguments to be added to the end of the URL.

If you have an idea for how the API should work differently, please explain what you mean with some examples.
