### ISSUE TITLE
Option to not display anything if there is only 1 page of elements?

### ISSUE THREAD

**Issue by nicolasblanco** [mgwidmann/scrivener_html#75]
Do you think it could be useful to add an option to not display any links if there is only 1 page in the elements?

**Comment by mgwidmann** [comment]
So no output at all instead of the current page?

**Comment by nicolasblanco** [comment]
@mgwidmann : what's the meaning of having a number or output if there's no additional page? In many cases I don't want output if there's just a single page. 👍

**Comment by mgwidmann** [comment]
@nicolasblanco Most designs want to signify to the user where the pagination links would be if any pages were available. Putting the number indicates this and informs the user that there are no pages to look through rather than having the user hunt around the site looking for something that doesn't exist.

I'm closing this issue as there doesn't seem to be a need for this feature.
