### ISSUE TITLE
Style not applied

### ISSUE THREAD

**Issue by popo63301** [mgwidmann/scrivener_html#85]
Hi people ! 

I'm using version "1.8" of the library and after following the installation process, I got the "pagination_links" without being styled like below:

![screenshot 2019-02-22 at 21 57 00](https://user-images.githubusercontent.com/29427340/53271870-fd85d180-36ef-11e9-83b8-8ce756403d21.png)

Any idea how to solve this issue?

**Comment by mgwidmann** [comment]
The default is to use bootstrap. If you are not using the bootstrap library, then it will look like a list (since bootstrap uses `<li>` elements for each page). The list of all css libraries supported are here: https://github.com/mgwidmann/scrivener_html#view-styles

If yours is not in the list, feel free to submit a PR to add it, but each CSS library tends to have its own customized way of displaying pagination links and thats what this library is for.
